services:
  redis:
    image: redis:alpine
    container_name: axieboard_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/redis:/usr/local/etc/redis
